// proto/helloworld.proto

// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file proto/hello.proto (package helloworld, syntax proto3)

import { HelloReplySchema, HelloRequestSchema } from './hello_pb';

/**
 * @generated from service helloworld.Greeter
 */
export const Greeter = {
  typeName: 'helloworld.Greeter',
  methods: {
    /**
     * @generated from rpc helloworld.Greeter.SayHello
     */
    sayHello: {
      name: 'SayHello',
      I: HelloRequestSchema,
      O: HelloReplySchema,
      kind: 'unary',
    },
  },
} as const;
